//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweeterReader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCCrimeReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GCCrimeReport()
        {
            this.GCCrimeReportNotes = new HashSet<GCCrimeReportNote>();
        }
    
        public int CrimeReportID { get; set; }
        public int CrimeReporterID { get; set; }
        public int CrimeFighterID { get; set; }
        public Nullable<int> CrimeSuspectID { get; set; }
        public string Evidence { get; set; }
        public int CrimeLocationID { get; set; }
        public string CrimeDescription { get; set; }
        public System.DateTime CrimeTimeSubmission { get; set; }
        public Nullable<System.DateTime> CrimeTimeResolved { get; set; }
        public int CrimeReportStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCCrimeReportNote> GCCrimeReportNotes { get; set; }
        public virtual GCCrimeReportStatu GCCrimeReportStatu { get; set; }
        public virtual GCLocation GCLocation { get; set; }
        public virtual GCPerson GCPerson { get; set; }
        public virtual GCPerson GCPerson1 { get; set; }
        public virtual GCPerson GCPerson2 { get; set; }
    }
}
