//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweeterReader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCPersonStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GCPersonStatu()
        {
            this.GCPersons = new HashSet<GCPerson>();
        }
    
        public int PersonStatusID { get; set; }
        public string PersonStatusName { get; set; }
        public string PersonStatusDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCPerson> GCPersons { get; set; }
    }
}
