//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweeterReader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GCPerson()
        {
            this.GCCrimeReportNotes = new HashSet<GCCrimeReportNote>();
            this.GCCrimeReports = new HashSet<GCCrimeReport>();
            this.GCCrimeReports1 = new HashSet<GCCrimeReport>();
            this.GCCrimeReports2 = new HashSet<GCCrimeReport>();
        }
    
        public int PersonID { get; set; }
        public string PersonFName { get; set; }
        public string PersonLName { get; set; }
        public string PersonAlias { get; set; }
        public string ContactPhone { get; set; }
        public int PersonLocationID { get; set; }
        public int AffiliationID { get; set; }
        public string Occupation { get; set; }
        public int PersonStatusID { get; set; }
        public string PersonNotableFeatures { get; set; }
        public Nullable<byte> TrustRating { get; set; }
        public string PersonImage { get; set; }
        public string PersonEmail { get; set; }
    
        public virtual GCAffiliation GCAffiliation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCCrimeReportNote> GCCrimeReportNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCCrimeReport> GCCrimeReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCCrimeReport> GCCrimeReports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCCrimeReport> GCCrimeReports2 { get; set; }
        public virtual GCLocation GCLocation { get; set; }
        public virtual GCPersonStatu GCPersonStatu { get; set; }
    }
}
